###
GET {{host}}/test/get
Authorization: eyJraWQiOiJFRjRGMjJDMC01Q0IwLTQzNDgtOTY3Qi0wMjY0OTVFN0VGQzgiLCJhbGciOiJFUzI1NiJ9.eyJpc3MiOiJjb20uemhpaHVpc2h1IiwiYXVkIjoicGMiLCJzdWIiOiJ0b20iLCJpYXQiOjE2NTY2NTU4MzQsImV4cCI6MTY1NzM3NTgzNCwianRpIjoiYzBjM2UwOTMtMzZiMi00YTk2LWFiMTgtYmY3ZDhkNTdmMDhiIiwidWlkIjo4MTM5Mzk2MTksInJvbGUiOiJhZG1pbiJ9.hwiTBYkVLi_B5Hf0sXyqT3654jFv5TIImd7Qaf40nPDV245BxCMQQW5G7XAPHIlzMADxTWmcak8k8_ayJflN_w


###
GET {{host}}/user-service/haha/lala
Origin: https://docs.spring.io
Access-Control-Request-Headers: authorization
Access-Control-Request-Method: GET

###
OPTIONS {{host}}/user-service/haha/lala
Origin: https://docs.spring.io
Access-Control-Request-Headers: authorization
Access-Control-Request-Method: GET

###
GET {{host}}/test/get
Origin: https://docs.spring.io
#Access-Control-Request-Headers: authorization
#Access-Control-Request-Method: GET


###
GET https://httpbin.org/get
Origin: https://docs.spring.io
